services:
  postgres:
    image: postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: "Postgres2023!"
      POSTGRES_DB: authproject
    ports:
      - "5432:5432"
